### PR TITLE
Quick update to 1.20.x

### PR DESCRIPTION
**Pull request by milkev**
Quick update to 1.20.x

There is no durability display on the item icon. I Just disabled the Item Render Mixin, I dont think its super important anyway as the tooltip is just as effective as the durability display when in a trinkets slot.

Reinstated PAL as JIJ, since that actually should be... my bad last time, sorry.

Also, I noticed the 1.17.x update wasn't updated on curseforge, and there is no available version of Shulker Charm on modrinth. If you have no intention of maintaining the updates/releases of Shulker Charm on curseforge/modrinth, is it alright if I do so in your place?

### CODE REVIEW

**Comment by LemmaEOF** [comment]
You shouldn't need to do the item renderer mixin - items just Have a built-in "here's what color my bar should be and how big it should be" thing now, so you can just use that instead.

The 1.17.x update for Shulker Charm was originally going to be a commission, but the commissioner didn't pay up so I didn't upload it. I can definitely add you onto the projects if you'd like!

**Comment by milkev** [comment]
> You shouldn't need to do the item renderer mixin - items just Have a built-in "here's what color my bar should be and how big it should be" thing now, so you can just use that instead.

Ok, ill look into that!

> The 1.17.x update for Shulker Charm was originally going to be a commission, but the commissioner didn't pay up so I didn't upload it. I can definitely add you onto the projects if you'd like!

Awww, thats unfortunate. I'd love to help maintain this mod, its one of the gems I really like.

**Comment by milkev** [comment]
Everything seems to be working for 1.20 and 1.20.1

The three main differences I've made compared to the master branch;
1) Changed config to Cloth Config. I already had it as this on my fork, and it seems much cleaner and easier to use than the jankson settup you had before. Atleast to me :P

2) Build.gradle has been replaced with the same settup I've used for my other mods... I think I had issues with your build.gradle when I originally made my fork, but honestly I'm not sure. I dont really know much about what build.gradle does aside from declaring repositories, dependencies, Java version & Loom lol. if it load I happy.

3) I made the durability bar disappear when 1 below max power, that way when you are flying at max charge within range of a beacon, the durability bar doesnt display.

Here is my curseforge & modrinth profiles;
[Curseforge Milkev](https://legacy.curseforge.com/members/milkev/projects)
[Modrinth Milkev](https://modrinth.com/user/milkev)

**Comment by LemmaEOF** [comment]
Sounds good! I'll get you added to this repo and curseforge, and you can publish it to Modrinth too!

**Pull request merged**
